version: '3'
services:
  ccs-app:
    image: ccs-app
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
  docker-postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres